# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/deployment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17models/deployment.proto\x12\ndeployment\"k\n\x0bMagicOutput\x12/\n\x06\x64\x65ploy\x18\x01 \x01(\x0b\x32\x1a.deployment.DeploymentInfoH\x00\x88\x01\x01\x12 \n\x03job\x18\x02 \x01(\x0b\x32\x13.deployment.JobInfoB\t\n\x07_deploy\"\x98\x01\n\x0e\x44\x65ploymentInfo\x12\x15\n\rdeployment_id\x18\x01 \x01(\t\x12\x11\n\tnode_list\x18\x02 \x03(\t\x12\x12\n\nnode_addrs\x18\x03 \x03(\t\x12\x33\n\x0bvllm_config\x18\x04 \x01(\x0b\x32\x1c.deployment.VllmDeployConfigH\x00\x42\x13\n\x11\x64\x65ployment_config\"C\n\x10VllmDeployConfig\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0f\n\x07tp_size\x18\x02 \x01(\x05\x12\x0f\n\x07pp_size\x18\x03 \x01(\x05\"\x9c\x01\n\x07JobInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x15\n\rdeployment_id\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\r\n\x05input\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\x12\x30\n\x0bvllm_config\x18\x06 \x01(\x0b\x32\x19.deployment.VllmRunConfigH\x00\x42\x0b\n\tjobConfig\"\x0f\n\rVllmRunConfig\"\xcd\x01\n\x07\x43ommand\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1a.deployment.Command.Action\x12\x35\n\x0f\x64\x65ployment_info\x18\x02 \x01(\x0b\x32\x1a.deployment.DeploymentInfoH\x00\x12\'\n\x08job_info\x18\x03 \x01(\x0b\x32\x13.deployment.JobInfoH\x00\"+\n\x06\x41\x63tion\x12\n\n\x06LAUNCH\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\x0c\n\x08TEARDOWN\x10\x02\x42\t\n\x07\x63ontextb\x06proto3')



_MAGICOUTPUT = DESCRIPTOR.message_types_by_name['MagicOutput']
_DEPLOYMENTINFO = DESCRIPTOR.message_types_by_name['DeploymentInfo']
_VLLMDEPLOYCONFIG = DESCRIPTOR.message_types_by_name['VllmDeployConfig']
_JOBINFO = DESCRIPTOR.message_types_by_name['JobInfo']
_VLLMRUNCONFIG = DESCRIPTOR.message_types_by_name['VllmRunConfig']
_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_COMMAND_ACTION = _COMMAND.enum_types_by_name['Action']
MagicOutput = _reflection.GeneratedProtocolMessageType('MagicOutput', (_message.Message,), {
  'DESCRIPTOR' : _MAGICOUTPUT,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.MagicOutput)
  })
_sym_db.RegisterMessage(MagicOutput)

DeploymentInfo = _reflection.GeneratedProtocolMessageType('DeploymentInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYMENTINFO,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.DeploymentInfo)
  })
_sym_db.RegisterMessage(DeploymentInfo)

VllmDeployConfig = _reflection.GeneratedProtocolMessageType('VllmDeployConfig', (_message.Message,), {
  'DESCRIPTOR' : _VLLMDEPLOYCONFIG,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.VllmDeployConfig)
  })
_sym_db.RegisterMessage(VllmDeployConfig)

JobInfo = _reflection.GeneratedProtocolMessageType('JobInfo', (_message.Message,), {
  'DESCRIPTOR' : _JOBINFO,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.JobInfo)
  })
_sym_db.RegisterMessage(JobInfo)

VllmRunConfig = _reflection.GeneratedProtocolMessageType('VllmRunConfig', (_message.Message,), {
  'DESCRIPTOR' : _VLLMRUNCONFIG,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.VllmRunConfig)
  })
_sym_db.RegisterMessage(VllmRunConfig)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'models.deployment_pb2'
  # @@protoc_insertion_point(class_scope:deployment.Command)
  })
_sym_db.RegisterMessage(Command)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAGICOUTPUT._serialized_start=39
  _MAGICOUTPUT._serialized_end=146
  _DEPLOYMENTINFO._serialized_start=149
  _DEPLOYMENTINFO._serialized_end=301
  _VLLMDEPLOYCONFIG._serialized_start=303
  _VLLMDEPLOYCONFIG._serialized_end=370
  _JOBINFO._serialized_start=373
  _JOBINFO._serialized_end=529
  _VLLMRUNCONFIG._serialized_start=531
  _VLLMRUNCONFIG._serialized_end=546
  _COMMAND._serialized_start=549
  _COMMAND._serialized_end=754
  _COMMAND_ACTION._serialized_start=700
  _COMMAND_ACTION._serialized_end=743
# @@protoc_insertion_point(module_scope)
