# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/resources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16models/resources.proto\x12\tresources\"f\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65vice_count\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65vice_type\x18\x03 \x01(\t\x12\x15\n\rdeployment_id\x18\x04 \x03(\t\x12\x0e\n\x06job_id\x18\x05 \x03(\t\"\xe8\x02\n\x06\x46\x61\x62ric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05nodes\x18\x02 \x03(\t\x12:\n\rdevice_counts\x18\x03 \x03(\x0b\x32#.resources.Fabric.DeviceCountsEntry\x12=\n\x0f\x64\x65vices_on_node\x18\x04 \x03(\x0b\x32$.resources.Fabric.DevicesOnNodeEntry\x1a\x33\n\x11\x44\x65viceCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1aU\n\x12\x44\x65vicesOnNodeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.resources.Fabric.DevicesOnNode:\x02\x38\x01\x1a:\n\rDevicesOnNode\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65vice_count\x18\x02 \x01(\x05\x62\x06proto3')



_NODE = DESCRIPTOR.message_types_by_name['Node']
_FABRIC = DESCRIPTOR.message_types_by_name['Fabric']
_FABRIC_DEVICECOUNTSENTRY = _FABRIC.nested_types_by_name['DeviceCountsEntry']
_FABRIC_DEVICESONNODEENTRY = _FABRIC.nested_types_by_name['DevicesOnNodeEntry']
_FABRIC_DEVICESONNODE = _FABRIC.nested_types_by_name['DevicesOnNode']
Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'models.resources_pb2'
  # @@protoc_insertion_point(class_scope:resources.Node)
  })
_sym_db.RegisterMessage(Node)

Fabric = _reflection.GeneratedProtocolMessageType('Fabric', (_message.Message,), {

  'DeviceCountsEntry' : _reflection.GeneratedProtocolMessageType('DeviceCountsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FABRIC_DEVICECOUNTSENTRY,
    '__module__' : 'models.resources_pb2'
    # @@protoc_insertion_point(class_scope:resources.Fabric.DeviceCountsEntry)
    })
  ,

  'DevicesOnNodeEntry' : _reflection.GeneratedProtocolMessageType('DevicesOnNodeEntry', (_message.Message,), {
    'DESCRIPTOR' : _FABRIC_DEVICESONNODEENTRY,
    '__module__' : 'models.resources_pb2'
    # @@protoc_insertion_point(class_scope:resources.Fabric.DevicesOnNodeEntry)
    })
  ,

  'DevicesOnNode' : _reflection.GeneratedProtocolMessageType('DevicesOnNode', (_message.Message,), {
    'DESCRIPTOR' : _FABRIC_DEVICESONNODE,
    '__module__' : 'models.resources_pb2'
    # @@protoc_insertion_point(class_scope:resources.Fabric.DevicesOnNode)
    })
  ,
  'DESCRIPTOR' : _FABRIC,
  '__module__' : 'models.resources_pb2'
  # @@protoc_insertion_point(class_scope:resources.Fabric)
  })
_sym_db.RegisterMessage(Fabric)
_sym_db.RegisterMessage(Fabric.DeviceCountsEntry)
_sym_db.RegisterMessage(Fabric.DevicesOnNodeEntry)
_sym_db.RegisterMessage(Fabric.DevicesOnNode)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FABRIC_DEVICECOUNTSENTRY._options = None
  _FABRIC_DEVICECOUNTSENTRY._serialized_options = b'8\001'
  _FABRIC_DEVICESONNODEENTRY._options = None
  _FABRIC_DEVICESONNODEENTRY._serialized_options = b'8\001'
  _NODE._serialized_start=37
  _NODE._serialized_end=139
  _FABRIC._serialized_start=142
  _FABRIC._serialized_end=502
  _FABRIC_DEVICECOUNTSENTRY._serialized_start=304
  _FABRIC_DEVICECOUNTSENTRY._serialized_end=355
  _FABRIC_DEVICESONNODEENTRY._serialized_start=357
  _FABRIC_DEVICESONNODEENTRY._serialized_end=442
  _FABRIC_DEVICESONNODE._serialized_start=444
  _FABRIC_DEVICESONNODE._serialized_end=502
# @@protoc_insertion_point(module_scope)
